-- AlterTable
ALTER TABLE "User" ADD COLUMN     "casinocommission" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "code" TEXT,
ADD COLUMN     "contactno" TEXT,
ADD COLUMN     "cshare" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "icshare" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "matchcommission" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "mobileshare" DOUBLE PRECISION NOT NULL DEFAULT 100,
ADD COLUMN     "reference" TEXT,
ADD COLUMN     "session_commission_type" TEXT NOT NULL DEFAULT 'No Comm',
ADD COLUMN     "sessioncommission" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "share" DOUBLE PRECISION NOT NULL DEFAULT 0;
