services:
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
  externalapi:
    build:
      context: .
      dockerfile: backend/externalapi/Dockerfile
    environment:
      NODE_ENV: development
      EXTERNAL_API_PORT: 4001
      REDIS_URL: redis://redis:6380
      REDIS_HOST: redis
      REDIS_PORT: 6380
      PG_URL: postgresql://postgres:8079@host.docker.internal:5432/betting_db
      JWT_SECRET: L9vY7z!pQkR#eA1dT3u*Xj5@FbNmC2Ws
      FRONTEND_URL: http://localhost:3000
      # Enable background systems for data population
      DISABLE_QUEUES: "0"
      DISABLE_SOCKETS: "0"
      DISABLE_WORKERS: "0"
    ports:
      - "4001:4001"
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  pgdata: